//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 NDD.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfig) DeepCopyInto(out *ControllerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfig.
func (in *ControllerConfig) DeepCopy() *ControllerConfig {
	if in == nil {
		return nil
	}
	out := new(ControllerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControllerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigBlock) DeepCopyInto(out *ControllerConfigBlock) {
	*out = *in
	if in.For != nil {
		in, out := &in.For, &out.For
		*out = new(ControllerConfigFor)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigBlock.
func (in *ControllerConfigBlock) DeepCopy() *ControllerConfigBlock {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigExecutor) DeepCopyInto(out *ControllerConfigExecutor) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Exec != nil {
		in, out := &in.Exec, &out.Exec
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigExecutor.
func (in *ControllerConfigExecutor) DeepCopy() *ControllerConfigExecutor {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigExecutor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigFor) DeepCopyInto(out *ControllerConfigFor) {
	*out = *in
	if in.Range != nil {
		in, out := &in.Range, &out.Range
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigFor.
func (in *ControllerConfigFor) DeepCopy() *ControllerConfigFor {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigFor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigFunction) DeepCopyInto(out *ControllerConfigFunction) {
	*out = *in
	in.ControllerConfigExecutor.DeepCopyInto(&out.ControllerConfigExecutor)
	if in.Vars != nil {
		in, out := &in.Vars, &out.Vars
		*out = make(map[string]ControllerConfigVar, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Input != nil {
		in, out := &in.Input, &out.Input
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigFunction.
func (in *ControllerConfigFunction) DeepCopy() *ControllerConfigFunction {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigFunction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigFunctionsBlock) DeepCopyInto(out *ControllerConfigFunctionsBlock) {
	*out = *in
	in.ControllerConfigBlock.DeepCopyInto(&out.ControllerConfigBlock)
	if in.ControllerConfigFunctions != nil {
		in, out := &in.ControllerConfigFunctions, &out.ControllerConfigFunctions
		*out = make(map[string]ControllerConfigFunction, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigFunctionsBlock.
func (in *ControllerConfigFunctionsBlock) DeepCopy() *ControllerConfigFunctionsBlock {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigFunctionsBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigGvrObject) DeepCopyInto(out *ControllerConfigGvrObject) {
	*out = *in
	in.ControllerConfigExecutor.DeepCopyInto(&out.ControllerConfigExecutor)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigGvrObject.
func (in *ControllerConfigGvrObject) DeepCopy() *ControllerConfigGvrObject {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigGvrObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigList) DeepCopyInto(out *ControllerConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ControllerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigList.
func (in *ControllerConfigList) DeepCopy() *ControllerConfigList {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControllerConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigMap) DeepCopyInto(out *ControllerConfigMap) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	in.ControllerConfigValue.DeepCopyInto(&out.ControllerConfigValue)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigMap.
func (in *ControllerConfigMap) DeepCopy() *ControllerConfigMap {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigProperties) DeepCopyInto(out *ControllerConfigProperties) {
	*out = *in
	if in.For != nil {
		in, out := &in.For, &out.For
		*out = make(map[string]ControllerConfigGvrObject, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Own != nil {
		in, out := &in.Own, &out.Own
		*out = make(map[string]ControllerConfigGvrObject, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Watch != nil {
		in, out := &in.Watch, &out.Watch
		*out = make(map[string]ControllerConfigGvrObject, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Vars != nil {
		in, out := &in.Vars, &out.Vars
		*out = make([]ControllerConfigVarBlock, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Functions != nil {
		in, out := &in.Functions, &out.Functions
		*out = make([]ControllerConfigFunctionsBlock, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]ControllerConfigFunctionsBlock, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigProperties.
func (in *ControllerConfigProperties) DeepCopy() *ControllerConfigProperties {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigQuery) DeepCopyInto(out *ControllerConfigQuery) {
	*out = *in
	if in.Query != nil {
		in, out := &in.Query, &out.Query
		*out = new(string)
		**out = **in
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(ControllerConfigSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigQuery.
func (in *ControllerConfigQuery) DeepCopy() *ControllerConfigQuery {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigSelector) DeepCopyInto(out *ControllerConfigSelector) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigSelector.
func (in *ControllerConfigSelector) DeepCopy() *ControllerConfigSelector {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigSlice) DeepCopyInto(out *ControllerConfigSlice) {
	*out = *in
	in.ControllerConfigValue.DeepCopyInto(&out.ControllerConfigValue)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigSlice.
func (in *ControllerConfigSlice) DeepCopy() *ControllerConfigSlice {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigSlice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigSpec) DeepCopyInto(out *ControllerConfigSpec) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = new(ControllerConfigProperties)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigSpec.
func (in *ControllerConfigSpec) DeepCopy() *ControllerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigStatus) DeepCopyInto(out *ControllerConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigStatus.
func (in *ControllerConfigStatus) DeepCopy() *ControllerConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigValue) DeepCopyInto(out *ControllerConfigValue) {
	*out = *in
	in.ControllerConfigQuery.DeepCopyInto(&out.ControllerConfigQuery)
	if in.String != nil {
		in, out := &in.String, &out.String
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigValue.
func (in *ControllerConfigValue) DeepCopy() *ControllerConfigValue {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigVar) DeepCopyInto(out *ControllerConfigVar) {
	*out = *in
	if in.Slice != nil {
		in, out := &in.Slice, &out.Slice
		*out = new(ControllerConfigSlice)
		(*in).DeepCopyInto(*out)
	}
	if in.Map != nil {
		in, out := &in.Map, &out.Map
		*out = new(ControllerConfigMap)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigVar.
func (in *ControllerConfigVar) DeepCopy() *ControllerConfigVar {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigVar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigVarBlock) DeepCopyInto(out *ControllerConfigVarBlock) {
	*out = *in
	in.ControllerConfigBlock.DeepCopyInto(&out.ControllerConfigBlock)
	if in.ControllerConfigVariables != nil {
		in, out := &in.ControllerConfigVariables, &out.ControllerConfigVariables
		*out = make(map[string]ControllerConfigVar, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigVarBlock.
func (in *ControllerConfigVarBlock) DeepCopy() *ControllerConfigVarBlock {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigVarBlock)
	in.DeepCopyInto(out)
	return out
}
