apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: lcnc-runtime
    app.kubernetes.io/part-of: lcnc-runtime
    app.kubernetes.io/version: tbd
  name: lcnc-runtime-controller-porch-role
rules:
- apiGroups:
  - porch.kpt.dev
  resources:
  - packagerevisionresources
  - packagerevisions
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - porch.kpt.dev
  resources:
  - packagerevisionresources/status
  - packagerevisions/status
  - packagerevisions/approval
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - lcnc.yndd.io
  resources:
  - controllerconfigs
  - controllerconfigs/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
